name: obento-project
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi:0.1.0
    container_name: obento-web
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/example
    volumes:
      - ./certs:/app/certs
    env_file:
      - .env
    depends_on:
      - db  # DB遅延実行
    networks:
      - backend_network

  db:
    image: postgres:15
    container_name: obento-db
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:

networks:
  backend_network:
    driver: bridge
