name: obento-project
services:
  db:
    image: postgres:15
    container_name: obento-db
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi:0.1.0
    container_name: obento-web
    ports:
      - "8000:8000"
    # environment:
    #   - TZ=Asia/Tokyo
    volumes:
      - ./certs:/app/certs
      - ./logs:/app/logs
      - ./order_logs:/app/order_logs
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy  # dbが健全になるまで待機
    networks:
      - backend_network

volumes:
  db-data:

networks:
  backend_network:
    driver: bridge