services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/Backend/app
      - ./app/core/my-local.key:/Backend/app/core/my-local.key
      - ./app/core/my-local.crt:/Backend/app/core/my-local.crt
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 192.168.3.14
      --port 8000
      --ssl-keyfile=/Backend/app/core/my-local.key
      --ssl-certfile=/Backend/app/core/my-local.crt
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend_network

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
