openapi: 3.0.0
info:
  title: Bento Ordering API
  description: API for ordering bento lunches
  version: 1.0.0
servers:
  - url: https://localhost:8000/
    description: Development server
  - url: https://www.sample.com
    description: Production server
paths:
  /:
    get:
      summary: ログイン画面表示
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ログイン画面
          content:
            text/html:
              schema:
                type: string
                example: login.html
components:
  responses:
    '200':
      description: ユーザー注文履歴取得成功
    '401':
      description: 未認証
