"""Postsテーブルを追加した

Revision ID: 7810ea06aed3
Revises: f0b836dbd4ee
Create Date: 2025-05-10 14:35:12.852856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, inspect

# revision identifiers, used by Alembic.
revision: str = '7810ea06aed3'
down_revision: Union[str, None] = 'f0b836dbd4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    if "posts" not in inspector.get_table_names():
        op.create_table(
            'posts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('content', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            schema='public'
        )
    op.create_index(op.f('ix_public_posts_id'), 'posts', ['id'], unique=False, schema='public')
    op.drop_table('Posts')
    op.create_index(op.f('ix_Companies_company_id'), 'Companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_Users_user_id'), 'Users', ['user_id'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_user_id'), table_name='Users')
    op.drop_index(op.f('ix_Companies_company_id'), table_name='Companies')
    op.create_table('Posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Posts_pkey')
    )
    op.drop_index(op.f('ix_public_posts_id'), table_name='posts', schema='public')
    op.drop_table('posts', schema='public')
    # ### end Alembic commands ###
