"""add expected_delivery_date to Orders

Revision ID: 7fb3df7dd898
Revises: 7810ea06aed3
Create Date: 2025-05-12 14:04:24.706063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb3df7dd898'
down_revision: Union[str, None] = '7810ea06aed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('expected_delivery_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'expected_delivery_date')
    # ### end Alembic commands ###
