"""add canceled column to Orders

Revision ID: fcf39177b19a
Revises: 7fb3df7dd898
Create Date: 2025-06-05 13:50:27.258117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf39177b19a'
down_revision: Union[str, None] = '7fb3df7dd898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('canceled', sa.Boolean(), nullable=True))

    # op.drop_column('Companies', 'update_at')
    # op.add_column('Menus', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.drop_column('Menus', 'update_at')
    # op.add_column('Orders', sa.Column('canceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'canceled')

    # op.drop_column('Orders', 'canceled')
    # op.add_column('Menus', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # op.drop_column('Menus', 'updated_at')
    # op.add_column('Companies', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
